### ISSUE TITLE
Upgrade to @testing-library/user-event 14

### ISSUE THREAD

**Issue by lifan0127** [storybookjs/testing-library#17]
The recommended user-event version is 14+ whereas this library still depends on v13. Any plan to update to v14?

> These docs describe user-event@14. We recommend updating your projects to this version, as it includes important bug fixes and new features. You can find the docs for user-event@13.5.0 [here](https://testing-library.com/docs/ecosystem-user-event).

https://testing-library.com/docs/user-event/install

**Comment by yannbf** [comment]
Hey @lifan0127 thanks for opening this issue! I'll take a look at this whenever I can!

**Comment by yannbf** [comment]
Hey @lifan0127 I released the update in `v0.0.10` but unfortunately had to downgrade @testing-library/user-event to version 13 again in `v0.0.11`. User event v14 is working ok for most projects, but projects using Svelte, Vue, HTML and Web components break because of an issue in one of user-event's dependencies.

If you are not affected by this problem and want to use `@storybook/testing-library` with user-event v14, you can use the `@storybook/testing-library@beta` version.

**Comment by lifan0127** [comment]
Thank you @yannbf ! Will give it a try

**Comment by anilanar** [comment]
>  but projects using Svelte, Vue, HTML and Web components break because of an issue in one of user-event's dependencies.

@yannbf Which dependency is that? Is there an upstream ticket that we can follow?

**Comment by JonathanKolnik** [comment]
@yannbf following up here, is there still an issue here upstream? If so could we cut a new beta version with user-event v14? Have a great weekend!

**Comment by tonvanalebeek** [comment]
> @yannbf following up here, is there still an issue here upstream? If so could we cut a new beta version with user-event v14? Have a great weekend!

Also interested in an upgrade to user-event v14

**Comment by yannbf** [comment]
Hey everyone! I'm taking a pass at this again, now for Storybook 7 projects, and the results seem promising.

I'm still doing some extensive testing to make sure it's good for every renderer we support. In the meantime, could you please try the following versions and get back to me on how it went?

```
Storybook 7.0.0:       0.1.1--canary.2ae3a98.0

Storybook 7.1.0 alpha: 0.1.1--canary.958fe40.0
```

**Comment by yannbf** [comment]
Hey everyone! Thanks a lot for your patience. 
The prior issues have been addressed and [@storybook/testing-library v0.2.0](https://github.com/storybookjs/testing-library/releases/tag/v0.2.0) has been released with upgraded versions of user-event and testing-library/dom. Please give it a try and let us know if you encounter any problems!
